sampleapp/guestbook_plus/urls.py
from django.conf.urls import url
from .views.comment_list_view import CommentListView
from .views.comment_thread_view import CommentThreadView

app_name = 'guestbook_plus'

urlpatterns = [
    url(r'^$', CommentListView.as_view(), name='base'),
    url(r'^comments/$', CommentListView.as_view(), name='comment_list'),
    url(r'^comments/(.+)/$', CommentThreadView.as_view(), name='comment_thread'),
]

sampleapp/sampleapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^guestbook/', include('guestbook_plus.urls')),
]

sampleapp/guestbook_plus/models.py
from django.db import models

# Create your models here.

sampleapp/guestbook_plus/models/comments.py
from django.db import models
import uuid

from .users import Commentator

class Comment(models.Model):
    comment_id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    title = models.CharField(max_length=100, blank=False)
    comment = models.TextField(blank=False)
    commentator = models.ForeignKey(to=Commentator, on_delete=models.CASCADE, blank=True)
    parent = models.ForeignKey('Comment', on_delete=models.CASCADE, related_name='oyako', null=True)
    append_at = models.DateTimeField(auto_now_add=True)

    def get_thread(self):
        """
        特定のcommentからcommentの所属するスレッド全体を取得する
        """

        comment = self
        while comment.parent is not None:
            comment = comment.parent
        
        self.tree = [comment]
        self.__get_leafs(root=comment)

        return self.tree
        
    
    def __get_leafs(self, root):
        leafs = Comment.objects.filter(parent=root)

        self.tree = self.tree + list(leafs)

        if leafs.count() == 0:
            return self.tree
        else:
            for leaf in leafs:
                self.__get_leafs(root=leaf)

sampleapp/guestbook_plus/models/users.py
from django.db import models
import uuid

class Commentator(models.Model):
    commentator_id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    name = models.CharField(max_length=50, default='名無しさん', blank=False, unique=True)

sampleapp/guestbook_plus/views/comment_list_view.py
from django.views.generic import View
from django.shortcuts import render, redirect
from ..models.comments import Comment
from ..models.users import Commentator
from django.core.exceptions import ObjectDoesNotExist

class CommentListView(View):
    def get(self, request, comment_id=None):
        comments = Comment.objects.filter(parent=None)
        response_params = {
            'comments': comments,
        }
        return render(request, 'comment_list.html', response_params)

    def post(self, request, comment_id=None):

        name = request.POST.get('name')

        commentator = None
        try:
            commentator = Commentator.objects.get(name=name)
        except ObjectDoesNotExist as err:
            print(err)

        if commentator is None:
            commentator = Commentator(name=name)
            commentator.save()

        title = request.POST.get('title')
        comment = request.POST.get('comment')

        if comment_id is None:
            # ルートコメント(新規スレッド作成の場合) 
            comment = Comment(
                title=title,
                comment=comment,
                commentator=commentator
            )
        else:
            # スレッドへの投稿の場合
            pass
        
        comment.save()

        print(commentator)

        comments = Comment.objects.filter(parent=None)

        response_params = {
            'comments': comments,
        }
        return redirect(to='/guestbook/comments/')
        # return render(request, 'comment_list.html', response_params)

sampleapp/guestbook_plus/views/comment_thread_view.py
from django.views.generic import View
from django.shortcuts import render, redirect
from ..models.comments import Comment
from ..models.users import Commentator
from django.core.exceptions import ObjectDoesNotExist


class CommentThreadView(View):


    def get(self, request, comment_id):
        root_comment = Comment.objects.get(comment_id=comment_id)
        response_params = {
            'title': root_comment.title,
            'comments': root_comment.get_thread(),
        }

        return render(request, 'comment_thread.html', response_params)

    def post(self, request, comment_id):
        parent = Comment.objects.get(comment_id=comment_id)

        commentator = None
        try:
            commentator = Commentator.objects.get(name=request.POST.get('name'))
        except ObjectDoesNotExist as err:
            commentator = Commentator(
                name=request.POST.get('name')
            )
            commentator.save()


        comment = Comment(
            title=request.POST.get('title'),
            comment=request.POST.get('comment'),
            commentator=commentator,
            parent=parent
        )
        comment.save()

        return self.get(request, comment_id=comment_id)

sampleapp/guestbook_plus/templates/base.html
<html>
    <head>
        <title>{% block title %}Sample{% endblock %}</title>
        {% load static %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/sticky-footer.css' %}" rel="stylesheet">
        <link href="{% static 'css/bootstrap-custom.css' %}" rel="stylesheet">
    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <!-- ヘッダーの文字 -->
                    <div class="navbar-brand">GuestBook Plus</div>
                </div>
            </div> 
        </nav>
        <div class="container" style="padding-top: 100px;">
        {% block content %}
        {% endblock %}
        </div>
        <footer class="footer">
            <div class="container">
                (C) Ryoma Fujiwara
            </div>
        </footer>
    </body>
</html>

sampleapp/guestbook_plus/templates/comment.html
<div class="bg-primary">
    <h3 id="{{ comment.comment_id }}">{{ comment.title }}</h3>
</div>
<div class="bg-info">
    By {{ comment.commentator.name }} 投稿日 {{ comment.append_at }}
</div>
<pre>
{{ comment.comment }}
</pre>
<h4>スレッドコメント</h4>
<form action="{% url 'guestbook_plus:comment_thread' comment.comment_id %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="title">コメントタイトル</label>
        <input type="text" class="form-control" name="title" id="title" placeholder="スレッドの名前"/>
    </div>
    <div class="form-group">
        <label for="name">名前</label>
        <input type="text" class="form-control" name="name" id="name" placeholder="投稿者の名前"/>
    </div>
    <div class="form-group">
        <label for="comment">メッセージ</label>
        <textarea class="form-control" name="comment" id="comment" rows="2" placeholder="投稿したいメッセージを入力してください"></textarea>
    </div>
    <button type="submit" class="btn btn-default">投稿</button>
</form>

sampleapp/guestbook_plus/templates/comment_list.html
{% extends 'base.html' %}
{% block title %}Comments{% endblock title %}
{% block content %}
    {% include 'thread_list.html' %}
    <hr/>
    {% for comment in comments %}
    {% include 'comment.html' %}
    <a href="{% url 'guestbook_plus:comment_thread' comment.comment_id %}" class="btn btn-dafault">スレッドを見る</a>
    {% endfor %}
    <hr/>
    {% include 'root_comment_form.html'  %}
{% endblock content %}

sampleapp/guestbook_plus/templates/comment_thread.html
{% extends 'base.html' %}
{% block title %}Comments{% endblock title %}
{% block content %}
<h1>{{ title }}</h1>
{% for comment in comments %}
{% include 'comment.html' %}
{% endfor %}
<a href="{% url 'guestbook_plus:comment_list' %}">トップに戻る</a>
{% endblock content %}

sampleapp/guestbook_plus/templates/root_comment_form.html
<!--新規スレッド開設用のフォーム-->
<form action="{% url 'guestbook_plus:comment_list' %}" method="POST">
    {% csrf_token %}
    <h2>新規スレッド開設</h2>
    <div class="form-group">
        <label for="title">スレッドタイトル</label>
        <input type="text" class="form-control" name="title" id="title" placeholder="スレッドの名前"/>
    </div>
    <div class="form-group">
        <label for="name">名前</label>
        <input type="text" class="form-control" name="name" id="name" placeholder="投稿者の名前"/>
    </div>
    <div class="form-group">
        <label for="comment">メッセージ</label>
        <textarea class="form-control" name="comment" id="comment" rows="10" placeholder="投稿したいメッセージを入力してください"></textarea>
    </div>
    <button type="submit" class="btn btn-default">投稿</button>
</form>

sampleapp/guestbook_plus/templates/thread_list.html
<div class="list-group">
    <div class="list-group-item active">スレッド一覧</div>
{% for comment in comments %}
    <a href="#{{ comment.comment_id }}" class="list-group-item">
        {{ comment.title }}
    </a>
{% endfor %}
</ul>